### ISSUE TITLE
Is there a way to reduce spam?

### ISSUE THREAD

**Issue by Jeffrey04** [huan/docker-simple-mail-forwarder#70]
when I go through the logs I see there are quite a number of spams going through the service, is there a way to somewhat block most, or at least some of it?

**Comment by JeffHiggy** [comment]
Just my 2 cents but the main reason I use this project is because it indiscriminately forwards everything, I can do the spam filtering on the receiving end where I can filter out to a spam folder vs just throwing out the email that may be a false positive.

There are similar projects that do quite a bit of spam checks.

**Comment by Jeffrey04** [comment]
my webhost block mail server entirely (hence my pull request to relay all mail sending work to my gmail smtp), so it would be nice to have some simple spam filtering done on server side so my gmail sent mail record get cleaner relatively
